### ISSUE TITLE
Find images to use for menu

### ISSUE THREAD

**Issue by jmankhan** [jmankhan/BergDiningApp#18]
We should probably get around 50 more on top of the ones we have. No need to spend a ton of time on assets before the code is functional. Remember to keep it opensource
@PaiHuoLong 
@bcross424

**Comment by jmankhan** [comment]
Also basic icons or design for the nutrition facts. Probably a bit more visually appealing than a nutrition label, and sticking to the material design. i'll look at some style guides

**Comment by PaiHuoLong** [comment]
Spent a few hours getting pics for everything on the first two days' menus. Also, cropped and re-sized all of them to be 250 x 250 px for uniformity. I'd like to have the images be a little bigger than they are currently showing and didn't want to have problems on high res devices.
