### ISSUE TITLE
Alter code to pull data from saved xml file

### ISSUE THREAD

**Issue by PaiHuoLong** [jmankhan/BergDiningApp#24]
App should use the .xml file that is saved on the device. upon start-up the app will check with server to verify it has the latest information.

**Comment by jmankhan** [comment]
Comparing different ways of doing this. Options include SQLite database, Realm library, SharedPreferences, and more. I am currently struggling with storing the version number, which will need to be sent from the server. Once I have developed a good design for this, I will update this issue
