### ISSUE TITLE
Create icons or styles for each station to display on menu

### ISSUE THREAD

**Issue by PaiHuoLong** [jmankhan/BergDiningApp#26]
Color coordinate and create aesthetically pleasing sorted list

@jmankhan

**Comment by jmankhan** [comment]
Bryan, please complete this over the weekend (11/22-11/23). 
We basically need a square image of a good indicator of each station. I would recommend making it 512 x 512. That way, we can easily scale it as we need.

**Comment by bcross424** [comment]
You got it.
