### ISSUE TITLE
Getting Familiar with Github

### ISSUE THREAD

**Issue by bcross424** [jmankhan/BergDiningApp#9]
Since I have never used GitHub before, I need to review and analyze how to participate with my team through GitHub.

**Comment by jmankhan** [comment]
Make sure you know how to assign people to tasks, explore and edit the wiki, and make and close issues. You can reference people with the @ character. @bcross424 

Look at the commit history, branches, and merging. 

That's all we need for this project at least, so when you've done all that close the issue
